[tool.poetry]
name = "backend"
version = "0.1.0"
description = "Reader Study Web API backend"
authors = ["Your Name <your.email@example.com>"]
readme = "README.md"
packages = [{include = "app"}]

[tool.poetry.dependencies]
python = "^3.13"
alembic = "^1.15.2"
fastapi = "^0.115.12"
psycopg2-binary = "^2.9.10"
pydantic = {extras = ["email"], version = "^2.11.4"}
pydantic-settings = "^2.0.0"
sqlalchemy = "^2.0.40"
uvicorn = "^0.34.2"
fastapi-users = {extras = ["sqlalchemy"], version = "^12.1.0"}
fastapi-users-db-sqlalchemy = "^5.0.0"
passlib = {extras = ["bcrypt"], version = "^1.7.4"}
python-jose = {extras = ["cryptography"], version = "^3.3.0"}
python-multipart = "^0.0.6"
python-dotenv = "^1.0.0"
httpx = "^0.24.1"
asyncpg = "^0.28.0"
aiosqlite = "^0.19.0"
bcrypt = "^4.0.1"
email-validator = "^2.0.0"

[tool.poetry.group.dev.dependencies]
pytest = "^8.3.5"
pytest-asyncio = "^0.23.5"
httpx = "^0.27.0"

[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
